# Main config file
---
- name: Play for setting up workstation
  hosts: localhost
  connection: local
  become: true # Enables sudo

  tasks:
    - name: Include packages
      ansible.builtin.include_tasks: tasks/packages.yml
