---
# Main config file

- name: Play for setting up workstation
  hosts: localhost
  connection: local
  become: true # Enables sudo

  pre_tasks:
    - name: Add package sources
      ansible.builtin.include_tasks: pre_tasks/package_source.yml

  tasks:
    - name: Install packages
      ansible.builtin.include_tasks: tasks/packages.yml
