---
# Main config file

- name: Play for setting up workstation
  hosts: localhost
  connection: local
  become: true # Enables sudo

  pre_tasks:
    - name: Performing pre tasks
      ansible.builtin.include_tasks: "{{ pre_task_name }}"
      loop: "{{ pre_task_names }}"
      loop_control:
        loop_var: pre_task_name
      vars:
        pre_task_names:
          - pre_tasks/required_packages.yml
          - pre_tasks/package_source.yml

  tasks:
    - name: Install packages
      ansible.builtin.include_tasks: tasks/packages.yml
