---
- name: Development related packages
  ansible.builtin.package:
    name:
      - diffoscope
      - git
      - hugo
      - plantuml
      - tmux
      - vim
      - zeal
    state: present

- name: Networking related packages
  ansible.builtin.package:
    name:
      - iperf
      - mosh
    state: present

- name: Utility packages
  ansible.builtin.package:
    name:
      - htop
      - keypassxc
      - pandoc
      - restic
      - stow
      - vlc
    state: present
